import type { ComponentType } from "react";
import type { ButtonProps } from "./button.ts";
import type { TextInputProps } from "./text-input.ts";
import type { TextAreaProps } from "./text-area.ts";
import type { NumberInputProps } from "./number-input.ts";
import type { QuantityInputProps } from "./quantity-input.ts";
import type { DateInputProps } from "./date-input.ts";
import type { DateTimeInputProps } from "./date-time-input.ts";
import type { TimeInputProps } from "./time-input.ts";
import type { SliderInputProps } from "./slider-input.ts";
import type { SpinnerInputProps } from "./spinner-input.ts";
import type { OptionSelectFieldProps } from "./option-select-field.ts";
import type { OptionsOrStringFieldProps } from "./options-or-string-field.ts";
import type { OptionAutocompleteFieldProps } from "./option-autocomplete-field.ts";
import type { OptionRadioGroupProps } from "./option-radio-group.ts";
import type { OptionCheckboxGroupProps } from "./option-checkbox-group.ts";
import type { TypedSuggestionInputProps } from "./typed-suggestion-input.ts";
import type { CodingInputProps } from "./coding-input.ts";
import type { ReferenceInputProps } from "./reference-input.ts";
import type { NodeErrorsProps } from "./node-errors.ts";
import type { NodeHeaderProps } from "./node-header.ts";
import type { NodeWrapperProps } from "./node-wrapper.ts";
import type { OptionsStatusProps } from "./options-status.ts";
import type { NodeHelpProps } from "./node-help.ts";
import type { NodeLegalProps } from "./node-legal.ts";
import type { NodeFlyoverProps } from "./node-flyover.ts";
import type { FormShellProps } from "./form-shell.ts";
import type { FormHeaderProps } from "./form-header.ts";
import type { FormErrorsProps } from "./form-errors.ts";
import type { NodesContainerProps } from "./nodes-container.ts";
import type { FormSectionProps } from "./form-section.ts";
import type { PageStatusProps } from "./page-status.ts";
import type { PageNavigationProps } from "./page-navigation.ts";
import type { EmptyStateProps } from "./empty-state.ts";
import type { FormActionsProps } from "./form-actions.ts";
import type { AnswerListProps } from "./answer-list.ts";
import type { AnswerRowProps } from "./answer-row.ts";
import type { GroupWrapperProps } from "./group-wrapper.ts";
import type { GroupItemProps } from "./group-item.ts";
import type { GroupContainerProps } from "./group-container.ts";
import type { GroupExtrasProps } from "./group-extras.ts";
import type { ChoiceMatrixProps } from "./choice-matrix.ts";
import type { GridTableProps } from "./grid-table.ts";
import type { AttachmentInputProps } from "./attachment-input.ts";
import type { DisplayNodeProps } from "./display-node.ts";
import type { OpenChoiceFieldProps } from "./open-choice.ts";
import type { TabContainerProps } from "./tab-container.ts";

export * from "./button.ts";
export * from "./text-input.ts";
export * from "./text-area.ts";
export * from "./number-input.ts";
export * from "./quantity-input.ts";
export * from "./date-input.ts";
export * from "./date-time-input.ts";
export * from "./time-input.ts";
export * from "./slider-input.ts";
export * from "./spinner-input.ts";
export * from "./option-entry.ts";
export * from "./option-select-field.ts";
export * from "./options-or-string-field.ts";
export * from "./option-autocomplete-field.ts";
export * from "./option-radio-group.ts";
export * from "./option-checkbox-group.ts";
export * from "./typed-suggestion-input.ts";
export * from "./coding-input.ts";
export * from "./reference-input.ts";
export * from "./node-errors.ts";
export * from "./node-header.ts";
export * from "./node-wrapper.ts";
export * from "./options-status.ts";
export * from "./node-help.ts";
export * from "./node-legal.ts";
export * from "./node-flyover.ts";
export * from "./form-shell.ts";
export * from "./form-header.ts";
export * from "./form-errors.ts";
export * from "./nodes-container.ts";
export * from "./form-section.ts";
export * from "./page-status.ts";
export * from "./page-navigation.ts";
export * from "./empty-state.ts";
export * from "./form-actions.ts";
export * from "./answer-list.ts";
export * from "./answer-row.ts";
export * from "./group-wrapper.ts";
export * from "./group-item.ts";
export * from "./group-container.ts";
export * from "./group-extras.ts";
export * from "./choice-matrix.ts";
export * from "./grid-table.ts";
export * from "./attachment-input.ts";
export * from "./display-node.ts";
export * from "./open-choice.ts";
export * from "./tab-container.ts";

export type Theme = {
  Button: ComponentType<ButtonProps>;
  TextInput: ComponentType<TextInputProps>;
  TextArea: ComponentType<TextAreaProps>;
  NumberInput: ComponentType<NumberInputProps>;
  QuantityInput: ComponentType<QuantityInputProps>;
  DateInput: ComponentType<DateInputProps>;
  DateTimeInput: ComponentType<DateTimeInputProps>;
  TimeInput: ComponentType<TimeInputProps>;
  SliderInput: ComponentType<SliderInputProps>;
  SpinnerInput: ComponentType<SpinnerInputProps>;
  OptionSelectField: ComponentType<OptionSelectFieldProps>;
  OptionsOrStringField: ComponentType<OptionsOrStringFieldProps>;
  OptionAutocompleteField: ComponentType<OptionAutocompleteFieldProps>;
  OptionRadioGroup: ComponentType<OptionRadioGroupProps>;
  OptionCheckboxGroup: ComponentType<OptionCheckboxGroupProps>;
  TypedSuggestionInput: ComponentType<TypedSuggestionInputProps>;
  CodingInput: ComponentType<CodingInputProps>;
  ReferenceInput: ComponentType<ReferenceInputProps>;
  NodeErrors: ComponentType<NodeErrorsProps>;
  NodeHeader: ComponentType<NodeHeaderProps>;
  NodeWrapper: ComponentType<NodeWrapperProps>;
  OptionsStatus: ComponentType<OptionsStatusProps>;
  NodeHelp: ComponentType<NodeHelpProps>;
  NodeLegal: ComponentType<NodeLegalProps>;
  NodeFlyover: ComponentType<NodeFlyoverProps>;
  FormShell: ComponentType<FormShellProps>;
  FormHeader: ComponentType<FormHeaderProps>;
  FormErrors: ComponentType<FormErrorsProps>;
  NodesContainer: ComponentType<NodesContainerProps>;
  FormSection: ComponentType<FormSectionProps>;
  PageStatus: ComponentType<PageStatusProps>;
  PageNavigation: ComponentType<PageNavigationProps>;
  EmptyState: ComponentType<EmptyStateProps>;
  FormActions: ComponentType<FormActionsProps>;
  AnswerList: ComponentType<AnswerListProps>;
  AnswerRow: ComponentType<AnswerRowProps>;
  GroupWrapper: ComponentType<GroupWrapperProps>;
  GroupItem: ComponentType<GroupItemProps>;
  GroupContainer: ComponentType<GroupContainerProps>;
  GroupExtras: ComponentType<GroupExtrasProps>;
  ChoiceMatrix: ComponentType<ChoiceMatrixProps>;
  GridTable: ComponentType<GridTableProps>;
  AttachmentInput: ComponentType<AttachmentInputProps>;
  DisplayNode: ComponentType<DisplayNodeProps>;
  OpenChoiceField: ComponentType<OpenChoiceFieldProps>;
  TabContainer: ComponentType<TabContainerProps>;
};
