import type { ComponentType } from "react";
import type { ButtonProps } from "./button.ts";
import type { TextInputProps } from "./text-input.ts";
import type { TextAreaProps } from "./text-area.ts";
import type { NumberInputProps } from "./number-input.ts";
import type { DateInputProps } from "./date-input.ts";
import type { DateTimeInputProps } from "./date-time-input.ts";
import type { TimeInputProps } from "./time-input.ts";
import type { SliderInputProps } from "./slider-input.ts";
import type { SpinnerInputProps } from "./spinner-input.ts";
import type { SelectInputProps } from "./select-input.ts";
import type { RadioButtonListProps } from "./radio-button-list.ts";
import type { CheckboxListProps } from "./checkbox-list.ts";
import type { MultiSelectInputProps } from "./multi-select-input.ts";
import type { ErrorsProps } from "./errors.ts";
import type { NodeHeaderProps } from "./node-header.ts";
import type { QuestionScaffoldProps } from "./question-scaffold.ts";
import type { OptionsStateProps } from "./options-state.ts";
import type { NodeHelpProps } from "./node-help.ts";
import type { NodeLegalProps } from "./node-legal.ts";
import type { NodeFlyoverProps } from "./node-flyover.ts";
import type { FormProps } from "./form.ts";
import type { FormHeaderProps } from "./form-header.ts";
import type { FormErrorsProps } from "./form-errors.ts";
import type { NodeListProps } from "./node-list.ts";
import type { FormSectionProps } from "./form-section.ts";
import type { PageStatusProps } from "./page-status.ts";
import type { PageNavigationProps } from "./page-navigation.ts";
import type { EmptyStateProps } from "./empty-state.ts";
import type { FormActionsProps } from "./form-actions.ts";
import type { AnswerListProps } from "./answer-list.ts";
import type { AnswerScaffoldProps } from "./answer-scaffold.ts";
import type { GroupWrapperScaffoldProps } from "./group-wrapper-scaffold.ts";
import type { GroupWrapperScaffoldItemProps } from "./group-wrapper-scaffold-item.ts";
import type { GroupScaffoldProps } from "./group-scaffold.ts";
import type { GroupActionsProps } from "./group-actions.ts";
import type { GridTableProps } from "./grid-table.ts";
import type { InputGroupProps } from "./input-group.ts";
import type { FileInputProps } from "./file-input.ts";
import type { DisplayRendererProps } from "./display-renderer.ts";
import type { TabContainerProps } from "./tab-container.ts";
import type { LinkProps } from "./link.ts";

export * from "./button.ts";
export * from "./text-input.ts";
export * from "./text-area.ts";
export * from "./number-input.ts";
export * from "./date-input.ts";
export * from "./date-time-input.ts";
export * from "./time-input.ts";
export * from "./slider-input.ts";
export * from "./spinner-input.ts";
export * from "./option-entry.ts";
export * from "./select-input.ts";
export * from "./radio-button-list.ts";
export * from "./checkbox-list.ts";
export * from "./multi-select-input.ts";
export * from "./errors.ts";
export * from "./node-header.ts";
export * from "./question-scaffold.ts";
export * from "./options-state.ts";
export * from "./node-help.ts";
export * from "./node-legal.ts";
export * from "./node-flyover.ts";
export * from "./form.ts";
export * from "./form-header.ts";
export * from "./form-errors.ts";
export * from "./node-list.ts";
export * from "./form-section.ts";
export * from "./page-status.ts";
export * from "./page-navigation.ts";
export * from "./empty-state.ts";
export * from "./form-actions.ts";
export * from "./answer-list.ts";
export * from "./answer-scaffold.ts";
export * from "./group-wrapper-scaffold.ts";
export * from "./group-wrapper-scaffold-item.ts";
export * from "./group-scaffold.ts";
export * from "./group-actions.ts";
export * from "./grid-table.ts";
export * from "./input-group.ts";
export * from "./file-input.ts";
export * from "./display-renderer.ts";
export * from "./tab-container.ts";
export * from "./link.ts";

export type Theme = {
  Button: ComponentType<ButtonProps>;
  TextInput: ComponentType<TextInputProps>;
  TextArea: ComponentType<TextAreaProps>;
  NumberInput: ComponentType<NumberInputProps>;
  DateInput: ComponentType<DateInputProps>;
  DateTimeInput: ComponentType<DateTimeInputProps>;
  TimeInput: ComponentType<TimeInputProps>;
  SliderInput: ComponentType<SliderInputProps>;
  SpinnerInput: ComponentType<SpinnerInputProps>;
  SelectInput: ComponentType<SelectInputProps>;
  RadioButtonList: ComponentType<RadioButtonListProps>;
  CheckboxList: ComponentType<CheckboxListProps>;
  MultiSelectInput: ComponentType<MultiSelectInputProps>;
  Errors: ComponentType<ErrorsProps>;
  NodeHeader: ComponentType<NodeHeaderProps>;
  QuestionScaffold: ComponentType<QuestionScaffoldProps>;
  OptionsState: ComponentType<OptionsStateProps>;
  NodeHelp: ComponentType<NodeHelpProps>;
  NodeLegal: ComponentType<NodeLegalProps>;
  NodeFlyover: ComponentType<NodeFlyoverProps>;
  Form: ComponentType<FormProps>;
  FormHeader: ComponentType<FormHeaderProps>;
  FormErrors: ComponentType<FormErrorsProps>;
  NodeList: ComponentType<NodeListProps>;
  FormSection: ComponentType<FormSectionProps>;
  PageStatus: ComponentType<PageStatusProps>;
  PageNavigation: ComponentType<PageNavigationProps>;
  EmptyState: ComponentType<EmptyStateProps>;
  FormActions: ComponentType<FormActionsProps>;
  AnswerList: ComponentType<AnswerListProps>;
  AnswerScaffold: ComponentType<AnswerScaffoldProps>;
  GroupWrapperScaffold: ComponentType<GroupWrapperScaffoldProps>;
  GroupWrapperScaffoldItem: ComponentType<GroupWrapperScaffoldItemProps>;
  GroupScaffold: ComponentType<GroupScaffoldProps>;
  GroupActions: ComponentType<GroupActionsProps>;
  GridTable: ComponentType<GridTableProps>;
  InputGroup: ComponentType<InputGroupProps>;
  FileInput: ComponentType<FileInputProps>;
  DisplayRenderer: ComponentType<DisplayRendererProps>;
  TabContainer: ComponentType<TabContainerProps>;
  Link: ComponentType<LinkProps>;
};
