import type { ComponentType } from "react";
import type { ButtonProps } from "./button.ts";
import type { TextInputProps } from "./text-input.ts";
import type { TextAreaProps } from "./text-area.ts";
import type { NumberInputProps } from "./number-input.ts";
import type { QuantityInputProps } from "./quantity-input.ts";
import type { DateInputProps } from "./date-input.ts";
import type { DateTimeInputProps } from "./date-time-input.ts";
import type { TimeInputProps } from "./time-input.ts";
import type { SliderInputProps } from "./slider-input.ts";
import type { SpinnerInputProps } from "./spinner-input.ts";
import type { SelectFieldProps } from "./select-field.ts";
import type { SelectOrStringFieldProps } from "./select-or-string-field.ts";
import type { AutocompleteFieldProps } from "./autocomplete-field.ts";
import type { RadioGroupProps } from "./radio-group.ts";
import type { CheckboxGroupProps } from "./checkbox-group.ts";
import type { MultiSelectFieldProps } from "./multi-select-field.ts";
import type { TypedAutocompleteInputProps } from "./typed-autocomplete-input.ts";
import type { CodingInputProps } from "./coding-input.ts";
import type { ReferenceInputProps } from "./reference-input.ts";
import type { NodeErrorsProps } from "./node-errors.ts";
import type { NodeHeaderProps } from "./node-header.ts";
import type { NodeWrapperProps } from "./node-wrapper.ts";
import type { OptionsStateProps } from "./options-state.ts";
import type { NodeHelpProps } from "./node-help.ts";
import type { NodeLegalProps } from "./node-legal.ts";
import type { NodeFlyoverProps } from "./node-flyover.ts";
import type { FormShellProps } from "./form-shell.ts";
import type { FormHeaderProps } from "./form-header.ts";
import type { FormErrorsProps } from "./form-errors.ts";
import type { NodeListProps } from "./node-list.ts";
import type { FormSectionProps } from "./form-section.ts";
import type { PageStatusProps } from "./page-status.ts";
import type { PageNavigationProps } from "./page-navigation.ts";
import type { EmptyStateProps } from "./empty-state.ts";
import type { FormActionsProps } from "./form-actions.ts";
import type { AnswerListProps } from "./answer-list.ts";
import type { AnswerRowProps } from "./answer-row.ts";
import type { RepeatingGroupListProps } from "./repeating-group-list.ts";
import type { GroupHeaderProps } from "./group-header.ts";
import type { GroupBodyProps } from "./group-body.ts";
import type { GroupActionsProps } from "./group-actions.ts";
import type { SelectionMatrixProps } from "./selection-matrix.ts";
import type { GridTableProps } from "./grid-table.ts";
import type { AttachmentInputProps } from "./attachment-input.ts";
import type { DisplayRendererProps } from "./display-renderer.ts";
import type { SelectOrInputFieldProps } from "./select-or-input-field.ts";
import type { TabContainerProps } from "./tab-container.ts";
import type { LinkProps } from "./link.ts";

export * from "./button.ts";
export * from "./text-input.ts";
export * from "./text-area.ts";
export * from "./number-input.ts";
export * from "./quantity-input.ts";
export * from "./date-input.ts";
export * from "./date-time-input.ts";
export * from "./time-input.ts";
export * from "./slider-input.ts";
export * from "./spinner-input.ts";
export * from "./option-entry.ts";
export * from "./select-field.ts";
export * from "./select-or-string-field.ts";
export * from "./autocomplete-field.ts";
export * from "./radio-group.ts";
export * from "./checkbox-group.ts";
export * from "./multi-select-field.ts";
export * from "./typed-autocomplete-input.ts";
export * from "./coding-input.ts";
export * from "./reference-input.ts";
export * from "./node-errors.ts";
export * from "./node-header.ts";
export * from "./node-wrapper.ts";
export * from "./options-state.ts";
export * from "./node-help.ts";
export * from "./node-legal.ts";
export * from "./node-flyover.ts";
export * from "./form-shell.ts";
export * from "./form-header.ts";
export * from "./form-errors.ts";
export * from "./node-list.ts";
export * from "./form-section.ts";
export * from "./page-status.ts";
export * from "./page-navigation.ts";
export * from "./empty-state.ts";
export * from "./form-actions.ts";
export * from "./answer-list.ts";
export * from "./answer-row.ts";
export * from "./repeating-group-list.ts";
export * from "./group-header.ts";
export * from "./group-body.ts";
export * from "./group-actions.ts";
export * from "./selection-matrix.ts";
export * from "./grid-table.ts";
export * from "./attachment-input.ts";
export * from "./display-renderer.ts";
export * from "./select-or-input-field.ts";
export * from "./tab-container.ts";
export * from "./link.ts";

export type Theme = {
  Button: ComponentType<ButtonProps>;
  TextInput: ComponentType<TextInputProps>;
  TextArea: ComponentType<TextAreaProps>;
  NumberInput: ComponentType<NumberInputProps>;
  QuantityInput: ComponentType<QuantityInputProps>;
  DateInput: ComponentType<DateInputProps>;
  DateTimeInput: ComponentType<DateTimeInputProps>;
  TimeInput: ComponentType<TimeInputProps>;
  SliderInput: ComponentType<SliderInputProps>;
  SpinnerInput: ComponentType<SpinnerInputProps>;
  SelectField: ComponentType<SelectFieldProps>;
  SelectOrStringField: ComponentType<SelectOrStringFieldProps>;
  AutocompleteField: ComponentType<AutocompleteFieldProps>;
  RadioGroup: ComponentType<RadioGroupProps>;
  CheckboxGroup: ComponentType<CheckboxGroupProps>;
  MultiSelectField: ComponentType<MultiSelectFieldProps>;
  TypedAutocompleteInput: ComponentType<TypedAutocompleteInputProps>;
  CodingInput: ComponentType<CodingInputProps>;
  ReferenceInput: ComponentType<ReferenceInputProps>;
  NodeErrors: ComponentType<NodeErrorsProps>;
  NodeHeader: ComponentType<NodeHeaderProps>;
  NodeWrapper: ComponentType<NodeWrapperProps>;
  OptionsState: ComponentType<OptionsStateProps>;
  NodeHelp: ComponentType<NodeHelpProps>;
  NodeLegal: ComponentType<NodeLegalProps>;
  NodeFlyover: ComponentType<NodeFlyoverProps>;
  FormShell: ComponentType<FormShellProps>;
  FormHeader: ComponentType<FormHeaderProps>;
  FormErrors: ComponentType<FormErrorsProps>;
  NodeList: ComponentType<NodeListProps>;
  FormSection: ComponentType<FormSectionProps>;
  PageStatus: ComponentType<PageStatusProps>;
  PageNavigation: ComponentType<PageNavigationProps>;
  EmptyState: ComponentType<EmptyStateProps>;
  FormActions: ComponentType<FormActionsProps>;
  AnswerList: ComponentType<AnswerListProps>;
  AnswerRow: ComponentType<AnswerRowProps>;
  RepeatingGroupList: ComponentType<RepeatingGroupListProps>;
  GroupHeader: ComponentType<GroupHeaderProps>;
  GroupBody: ComponentType<GroupBodyProps>;
  GroupActions: ComponentType<GroupActionsProps>;
  SelectionMatrix: ComponentType<SelectionMatrixProps>;
  GridTable: ComponentType<GridTableProps>;
  AttachmentInput: ComponentType<AttachmentInputProps>;
  DisplayRenderer: ComponentType<DisplayRendererProps>;
  SelectOrInputField: ComponentType<SelectOrInputFieldProps>;
  TabContainer: ComponentType<TabContainerProps>;
  Link: ComponentType<LinkProps>;
};
